CREATE TABLE Examples (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    SourceSentence TEXT NOT NULL,
    UsedWord TEXT NOT NULL,
    CorrectAnswer TEXT NOT NULL
);

CREATE TABLE AlternativeCorrectAnswers (
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    ExampleId INTEGER UNIQUE NOT NULL,
    Answer TEXT NOT NULL,
    
    FOREIGN KEY (ExampleId) REFERENCES Examples(Id) ON DELETE CASCADE ON UPDATE CASCADE
);


SELECT * FROM Examples

DELETE FROM Examples

DROP TABLE Examples

DROP TABLE AlternativeCorrectAnswers